### PR TITLE
introducing named manual screenshots

### PR DESCRIPTION
**Pull request by hutzelknecht**
so inside a test spec you can type this.takeScreenshot("empty form") and in the html output you can see the manual screenshots in addition to the "Result" output.

### CODE REVIEW

**Comment by jintoppy** [comment]
Please resolve conflicts

**Comment by hutzelknecht** [comment]
is there any way i can resolve the conflicts?

**Comment by jintoppy** [comment]
You might have to rebase your branch with the master and resolve the issues

**Comment by hutzelknecht** [comment]
try now! it should work

**Comment by jintoppy** [comment]
Still I am getting conflicts. :-(

**Comment by eddiemonge** [comment]
@hutzelknecht ^^

**Comment by hutzelknecht** [comment]
there are too many commits since my changes - code is unforested and doesn't have any comments. i see no end of the road with this. This kind of stuff happens when you wait too long to merge a branch. The fastest way to do this is propably to rewrite this functionality. I don't have time for it at the moment.

**Pull request closed without merging**
